wip

diff --git a/test/playground/sake.yaml b/test/playground/sake.yaml
--- a/test/playground/sake.yaml
+++ b/test/playground/sake.yaml
@@ -11,6 +11,15 @@ servers:
     local: true
     tags: [local]
 
+  # performance:
+  #   user: test
+  #   identity_file: ../keys/id_ed25519_pem_no
+  #   inventory: |
+  #     num_hosts=$((9999 + $SAKE_NUM_HOSTS))
+  #     for port in $(seq 10000 $num_hosts); do echo "0.0.0.0:$port"; done
+  #   env:
+  #     SAKE_NUM_HOSTS: 1
+
   list:
     desc: many hosts using list of hosts
     hosts:
@@ -187,19 +196,6 @@ env:
   DATE: $(date -u +"%Y-%m-%dT%H:%M:%S%Z")
 
 tasks:
-  register:
-    tasks:
-      - cmd: echo "foo" && >&2 echo "error"
-        register: out
-      - cmd: |
-          echo "status: $out_status"
-          echo "rc: $out_rc"
-          echo "failed: $out_failed"
-          echo "stdout: $out_stdout"
-          echo "stderr: $out_stderr"
-          echo "out:"
-          echo "$out"
-
   ping:
     target: all
     spec: host_pinned
@@ -256,3 +252,39 @@ tasks:
     spec: info
     target: all
     cmd: uname -r | awk -v FS='-' '{print $1}'
+
+  register:
+    tasks:
+      - cmd: echo "foo" && >&2 echo "error"
+        register: out
+      - cmd: |
+          echo "status: $out_status"
+          echo "rc: $out_rc"
+          echo "failed: $out_failed"
+          echo "stdout: $out_stdout"
+          echo "stderr: $out_stderr"
+          echo "out: $out"
+
+      - cmd: echo "xyz" && >&2 echo "error 2"
+        register: out2
+      - cmd: |
+          echo "status: $out_status"
+          echo "rc: $out_rc"
+          echo "failed: $out_failed"
+          echo "stdout: $out_stdout"
+          echo "stderr: $out_stderr"
+          echo "out: $out"
+
+          echo "-------------"
+
+          echo "status: $out2_status"
+          echo "rc: $out2_rc"
+          echo "failed: $out2_failed"
+          echo "stdout: $out2_stdout"
+          echo "stderr: $out2_stderr"
+          echo "out: $out2"
+
+  register2:
+    tasks:
+      - cmd: echo "foo" && >&2 echo "error"
+        register: out
diff --git a/test/tasks.yaml b/test/tasks.yaml
--- a/test/tasks.yaml
+++ b/test/tasks.yaml
@@ -200,6 +200,43 @@ tasks:
       - task: work-nested
         work_dir: /etc
 
+  ############
+  # REGISTER #
+  ############
+  register-1:
+    tasks:
+      - cmd: echo "foo"
+        register: out
+
+  register-2:
+    tasks:
+      - cmd: echo "foo"
+        register: out
+      - cmd: |
+          echo "status: $out_status"
+          echo "rc: $out_rc"
+          echo "failed: $out_failed"
+          echo "stdout: $out_stdout"
+          echo "stderr: $out_stderr"
+
+      - cmd: |
+          >&2 echo "error 2"
+        register: out2
+      - cmd: |
+          echo "status: $out_status"
+          echo "rc: $out_rc"
+          echo "failed: $out_failed"
+          echo "stdout: $out_stdout"
+          echo "stderr: $out_stderr"
+
+          echo "-------------"
+
+          echo "status: $out2_status"
+          echo "rc: $out2_rc"
+          echo "failed: $out2_failed"
+          echo "stdout: $out2_stdout"
+          echo "stderr: $out2_stderr"
+
   ########
   # Spec #
   ########
