wip

diff --git a/test/playground/sake.yaml b/test/playground/sake.yaml
--- a/test/playground/sake.yaml
+++ b/test/playground/sake.yaml
@@ -1,5 +1,5 @@
 import:
-  - ./tasks.yaml
+  - ./tasks/tasks.yaml
 
 known_hosts_file: known_hosts
 disable_verify_host: true
@@ -7,9 +7,18 @@ disable_verify_host: true
 servers:
   localhost:
     desc: localhost
-    host: localhost
+    host: 0.0.0.0
     local: true
     tags: [local]
+
+  remote:
+    host: 0.0.0.0
+    # host: 172.24.2.2
+    local: true
+    # user: test
+    # identity_file: ../keys/id_ed25519_pem_no
+    # work_dir: does_not_exist
+    tags: [kaka]
 
   list:
     desc: many hosts using list of hosts
@@ -49,13 +58,13 @@ servers:
   server-1:
     desc: server-1 desc
     host: sake-resolve
-    tags: [remote, pi]
+    tags: [remote, pi, bastion]
     work_dir: /tmp
 
   server-2:
     desc: server-2 desc
     host: sake-resolve
-    tags: [remote, pi]
+    tags: [remote, pi, bastion]
 
   server-3:
     desc: server-3 desc
@@ -63,6 +72,8 @@ servers:
     user: test
     identity_file: ../keys/id_ed25519_pem_no
     tags: [remote, pi, pihole]
+    env:
+      FOO: 123
 
   server-4:
     desc: server-4 desc
@@ -136,6 +147,33 @@ specs:
     ignore_unreachable: true
     any_errors_fatal: false
 
+  linear:
+    desc: Linear
+    strategy: linear
+    # forks: 2
+    batch: 2
+    # batch_p: 50
+    output: text
+    ignore_errors: true
+    ignore_unreachable: false
+    any_errors_fatal: true
+    # max_fail_percentage: 60
+    report: [recap]
+
+  host_pinned:
+    desc: Host Pinned
+    strategy: host_pinned
+    order: sorted
+    # forks: 2
+    batch: 2
+    # batch_p: 50
+    output: text
+    ignore_errors: true
+    ignore_unreachable: true
+    # any_errors_fatal: false
+    max_fail_percentage: 60
+    report: [recap]
+
   free:
     desc: Free
     strategy: free
@@ -147,167 +185,91 @@ specs:
     # any_errors_fatal: true
     max_fail_percentage: 60
 
-  row:
-    desc: Row
-    strategy: row
-    # forks: 2
-    batch: 2
-    # batch_p: 50
-    output: text
-    ignore_errors: false
-    ignore_unreachable: false
-    # any_errors_fatal: true
-    max_fail_percentage: 60
-    report: [basic]
-
-  column:
-    # desc: Column
-    strategy: column
-    # forks: 1
-    # batch: 1
-    # batch_p: 50
-    # output: text
-    # ignore_errors: false
-    # ignore_unreachable: true
-    ## any_errors_fatal: false
-    # max_fail_percentage: 59
+# themes:
+#   default:
+#     text:
+#       header: '{{ .Style "TASK" "bold" }} {{ .Name }}'
+#       header_filler: "-"
 
 env:
   VERSION: v0.1.0
   DATE: $(date -u +"%Y-%m-%dT%H:%M:%S%Z")
 
 tasks:
-  exit:
-    # target: all
-    # spec: column
+  register:
     tasks:
+      - cmd: echo "foo" && >&2 echo "error"
+        register: out
       - cmd: |
-          if [[ $SAKE_SERVER_NAME == "list-0" || $SAKE_SERVER_NAME == "list-2" ]]; then
-            exit 1
-          else
-            echo 123
-          fi
-          # sleep 1
-        ignore_errors: true
-      - cmd: |
-          if [[ $SAKE_SERVER_NAME == "list-1" || $SAKE_SERVER_NAME == "list-2" ]]; then
-            exit 1
-          else
-            echo 123
-          fi
-          # sleep 1
-        ignore_errors: true
-      - cmd: |
-          echo "DONE"
-
-          # for i in {1..5}
-          # do
-          #    sleep $(shuf -i1-4 -n1)
-          #    echo "$i"
-          # done
-          # exit 1
-
-  # register:
-  #   target: all
-  #   spec: row
-  #   desc: ping server
-  #   tasks:
-  #     - cmd: |
-  #         if [[ $SAKE_SERVER_HOST == "localhost" ]]; then
-  #           exit 1
-  #         else
-  #           sleep $(shuf -i1-2 -n1)
-  #           echo "$SAKE_SERVER_NAME"
-  #         fi
-
-  #         >&2 echo "error"
-  #         >&1 echo "stdout"
-  #         >&2 echo "error"
-  #         # sudo apt-get install htop -y
-  #         # sleep 2 && >&2 echo "error"
-  #         # >&1 echo "stdout"
-  #         # sleep 2 && >&2 echo "error"
-  #       register: hej
-  #     - cmd: echo $hej
-
-  #     # - cmd: |
-  #     #     echo 123
-  #     #     echo 345
-  #     #   register: kaka
-  #     # - cmd: |
-  #     #     if [[ $SAKE_TASK_EXIT == 1 ]]; then
-  #     #       echo $SAKE_TASK_EXIT
-  #     #     else
-  #     #       echo $SAKE_TASK_OUT
-  #     #     fi
-  #     #   register: kaka
-  #     # - cmd: |
-  #     #     # echo $hej
-  #     #     # echo $hej_stdout
-  #     #     echo "$hej_stderr"
-  #     #     # echo $hej_rc
-  #     #     # echo $hej_failed
-  #     #     # echo
-  #     #     # echo $kaka
-  #     #     # echo $kaka_rc
-  #     #     # echo $kaka_failed
-
-  # # exit:
-  # #   # name: hej
-  # #   local: true
-  # #   cmd: exit 3
+          echo "status: $out_status"
+          echo "rc: $out_rc"
+          echo "failed: $out_failed"
+          echo "stdout: $out_stdout"
+          echo "stderr: $out_stderr"
+          echo "out:"
+          echo "$out"
 
   # ping:
   #   target: all
-  #   spec: column
+  #   spec: host_pinned
   #   desc: ping server
-  #   # cmd: echo pong
+  #   cmd: echo pong
+
+  ping:
+    desc: Pong
+    target:
+      tags: [kaka]
+    # cmd: echo pong
+    tasks:
+      - cmd: echo pong
+
+  # exit:
+  #   # name: Exit
+  #   local: true
+  #   cmd: exit 3
+
+  # sleep:
+  #   desc: ping server
+  #   cmd: sleep 2 & echo done
+
+  # info:
+  #   name: Info
+  #   desc: print info
+  #   target: all
   #   tasks:
-  #     - cmd: echo 123
-  #     - cmd: echo 321
+  #     - task: print-host
+  #     - task: print-hostname
+  #     - task: print-os
+  #     - task: print-kernel
 
-  # # sleep:
-  # #   desc: ping server
-  # #   cmd: sleep 2 & echo done
+  # # Info
+  # print-host:
+  #   name: Host
+  #   desc: print host
+  #   spec: info
+  #   target: all
+  #   cmd: echo $S_HOST
 
-  # # info:
-  # #   name: Info
-  # #   desc: print info
-  # #   target: all
-  # #   tasks:
-  # #     - task: print-host
-  # #     - task: print-hostname
-  # #     - task: print-os
-  # #     - task: print-kernel
+  # print-hostname:
+  #   name: Hostname
+  #   desc: print hostname
+  #   spec: info
+  #   target: all
+  #   cmd: hostname
 
-  # # # Info
-  # # print-host:
-  # #   name: Host
-  # #   desc: print host
-  # #   spec: info
-  # #   target: all
-  # #   cmd: echo $SAKE_SERVER_HOST
+  # print-os:
+  #   name: OS
+  #   desc: print OS
+  #   spec: info
+  #   target: all
+  #   cmd: |
+  #     os=$(lsb_release -si)
+  #     release=$(lsb_release -sr)
+  #     echo "$os $release"
 
-  # # print-hostname:
-  # #   name: Hostname
-  # #   desc: print hostname
-  # #   spec: info
-  # #   target: all
-  # #   cmd: hostname
-
-  # # print-os:
-  # #   name: OS
-  # #   desc: print OS
-  # #   spec: info
-  # #   target: all
-  # #   cmd: |
-  # #     os=$(lsb_release -si)
-  # #     release=$(lsb_release -sr)
-  # #     echo "$os $release"
-
-  # # print-kernel:
-  # #   name: Kernel
-  # #   desc: Print kernel version
-  # #   spec: info
-  # #   target: all
-  # #   cmd: uname -r | awk -v FS='-' '{print $1}'
+  # print-kernel:
+  #   name: Kernel
+  #   desc: Print kernel version
+  #   spec: info
+  #   target: all
+  #   cmd: uname -r | awk -v FS='-' '{print $1}'
